### ISSUE TITLE
Create: Dynamic Villages incompatability

### ISSUE THREAD

**Issue by tangolikeelk** [cotrin8672/CreateEnchantableMachinery#10]
Because of the way Enchantable Machinery handles the drills and things like that, they are no longer recognized as job sites for [Dynamic Villages](https://www.curseforge.com/minecraft/mc-mods/dynamic-village)' villagers.

For additional info: I am on Forge 1.20.1 with version 1.0.2 of your mod, I did confirm that it is the interaction between the two mods. Removing only this mod allowed the villager to use a drill as a job block.

**Comment by cotrin8672** [comment]
Thanks for the report!
This modification replaces the default Mechanical Drill Block with an Enchantable Mechanical Drill Block, so the villagers do not recognize it as an occupational block, which may be causing the problem.

There are three possible solutions,
1 : Create: Individualized on the Enchantable Machinery side.
2 : Create: Handle it individually on the Dynamic Village side.
3 : Change the default Mechanical Drill Block to be placed only when an unenchanted block is placed.

Since 1 is difficult to achieve for technical reasons, and 2 is also dependent on the Create: Dynamic Village author's response, we are planning to release a patch within a few days that fixes the issue by adopting approach 3. This will allow the behavior of enchanted blocks to remain the same, but allow the use of unenchanted blocks when used as occupation blocks.

**Comment by tangolikeelk** [comment]
Sounds good and thank you for such a quick response!
