### ISSUE TITLE
drill cannot break blocks with enchantment silk touch

### ISSUE THREAD

**Issue by minhkhang45** [cotrin8672/CreateEnchantableMachinery#26]
drill cannot break blocks with enchantment silk touch

https://github.com/user-attachments/assets/7b839f2e-98c3-4c34-8119-19d35379f4dd

**Comment by cotrin8672** [comment]
Thank you for reporting this issue!

It seems similar to an issue we encountered before. Based on the problem description, it is likely that the FTB Chunks or another chunk protection mod is preventing the drill from breaking blocks. This happens because the chunk protection mod is blocking actions from FakePlayer, which the drill uses to interact with blocks.

To resolve this, please check the settings of the chunk protection mod (such as FTB Chunks) and make sure to allow FakePlayer interactions in the protected chunks.

You can refer to a similar solution discussed in this issue: #9.

When building issues in the future, please check past issues and include at least the information necessary to reproduce the bug, such as version and mod configuration.

**Comment by minhkhang45** [comment]
thank you, yes this is chunk protection by PneumaticCraft
