### ISSUE TITLE
Crash on v1.3.4

### ISSUE THREAD

**Issue by Oregano1963** [cotrin8672/CreateEnchantableMachinery#38]
logs: https://mclo.gs/CVJCncp

the crash doesn't happen without this mod enabled.

**Comment by cotrin8672** [comment]
I am not a volunteer. If you report a problem, at a minimum, please note the version of Minecraft and mods, and the minimum configuration of which mod combination causes the crash. At least in the environment with Create,KotlinForForge,Create: Enchantable Machinary, the problem is not happening, so the cause is in another mod that is installed.

**Comment by WeeskyBDW** [comment]
I have the same issue with Minecraft 1.18.2, Forge 40.2.17, Create 1.18.2-0.5.1.f, Create Enchantable Machinery 1.18.2-1.0.3 and KotlinForForge 3.12.0-all. I disabled (renamed .jar to .jar.disabled) all other create addons. 
![image](https://github.com/user-attachments/assets/d40775b8-78ad-432a-86d2-b2443b58c2ba)
Will try to update kotlinforforge and let you know

**Comment by cotrin8672** [comment]
I tried the exact same configuration and could not reproduce the problem at hand, please try updating the mod and see if that solves the problem.

**Comment by WeeskyBDW** [comment]
I updated the mod to the last 1.18.2 version and it work ! thanksI updated the mod to the last 1.18.2 version and it work ! thanks
